# Site settings
title:          레몬 공부방
description:    "Minimal Jekyll theme for storytellers"
baseurl:        ""
url:            "https://puuurm.github.io/"

# Author
author:
  name:         Lemon
  url:          https://puuurm.github.io/
  email:        wolla39@gmail.com
  github:       https://github.com/puuurm

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
